"""add threshold change to InventoryLog model

Revision ID: 2a1cea3ce68e
Revises: b45d44675d77
Create Date: 2025-09-26 12:39:28.912609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a1cea3ce68e'
down_revision = 'b45d44675d77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ▼▼▼ ここから修正 ▼▼▼ ---

    # 1. inventory_log に threshold_before 列を nullable=True で追加
    with op.batch_alter_table('inventory_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_before', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('threshold_after', sa.Integer(), nullable=True))

    # 2. 既存の inventory_log レコードの threshold_before/after にデフォルト値 (例: 0) を設定
    #    NOT NULL 制約を後で適用するために必要
    op.execute("UPDATE inventory_log SET threshold_before = 0 WHERE threshold_before IS NULL")
    op.execute("UPDATE inventory_log SET threshold_after = 0 WHERE threshold_after IS NULL")

    # 3. inventory_log の threshold_before/after 列の nullable を False に変更
    with op.batch_alter_table('inventory_log', schema=None) as batch_op:
        batch_op.alter_column('threshold_before',
                              existing_type=sa.Integer(),
                              nullable=False,
                              existing_nullable=True)
        batch_op.alter_column('threshold_after',
                              existing_type=sa.Integer(),
                              nullable=False,
                              existing_nullable=True)

    # product テーブルの price 列の型変更は意図しないため、コメントアウトまたは削除
    # もし、この変更が意図的なものなら、この行は残す
    # ただし、現状では整数型であるべきなので、通常は変更不要
    # with op.batch_alter_table('product', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.INTEGER(),
    #            type_=sa.String(length=128),
    #            existing_nullable=True)

    # --- ▲▲▲ 修正ここまで ▲▲▲ ---

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # --- ▼▼▼ ここから修正 ▼▼▼ ---

    # product テーブルの price 列の型変更をロールバックする操作は不要、または意図しないのでコメントアウト/削除
    # with op.batch_alter_table('product', schema=None) as batch_op:
    #     batch_op.alter_column('price',
    #            existing_type=sa.String(length=128),
    #            type_=sa.INTEGER(),
    #            existing_nullable=True)

    # inventory_log から threshold 列を削除
    with op.batch_alter_table('inventory_log', schema=None) as batch_op:
        batch_op.drop_column('threshold_after')
        batch_op.drop_column('threshold_before')

    # ### end Alembic commands ###