"""Add ProductLog model and fields

Revision ID: 7cf0870fe835
Revises: 
Create Date: 2025-09-27 00:12:50.472614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cf0870fe835'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=True)

    with op.batch_alter_table('product_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('change_set_id', sa.String(length=36), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_log', schema=None) as batch_op:
        batch_op.drop_column('change_set_id')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
