"""merge multiple heads

Revision ID: b45d44675d77
Revises: 05a2154df898, e888838958ec
Create Date: 2025-09-26 12:15:46.204140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45d44675d77'
down_revision = ('05a2154df898', 'e888838958ec')
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # cost列がまだDBに存在しない場合、ここで追加する
    # ### end Alembic commands ###
    pass


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    pass