"""Initial migration after cleanup

Revision ID: c267d4180fc0
Revises: 
Create Date: 2025-09-26 14:40:08.154344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c267d4180fc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/c267d4180fc0_initial_migration_after_cleanup.py
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=128),
               existing_nullable=True)
=======
    # with op.batch_alter_table('product', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))
    pass
>>>>>>> fix-inventoryLog:migrations/versions/e888838958ec_add_price_and_cost_to_product_model.py

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
<<<<<<< HEAD:migrations/versions/c267d4180fc0_initial_migration_after_cleanup.py
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(length=128),
               type_=sa.INTEGER(),
               existing_nullable=True)

=======
    # with op.batch_alter_table('product', schema=None) as batch_op:
    #     batch_op.drop_column('cost')
    #     batch_op.drop_column('price')
    pass
>>>>>>> fix-inventoryLog:migrations/versions/e888838958ec_add_price_and_cost_to_product_model.py
    # ### end Alembic commands ###
