"""add price and cost to Product model

Revision ID: e888838958ec
Revises: ae15902b73b6
Create Date: 2025-09-24 09:24:45.676704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e888838958ec'
down_revision = 'ae15902b73b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('product', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('price', sa.Integer(), nullable=True))
        # batch_op.add_column(sa.Column('cost', sa.Integer(), nullable=False))
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # with op.batch_alter_table('product', schema=None) as batch_op:
    #     batch_op.drop_column('cost')
    #     batch_op.drop_column('price')
    pass
    # ### end Alembic commands ###
